languageCode = "fr-fr"
title = "Morgan Eloy"
baseURL = "http://localhost:1313/"
SectionPagesManu ="main"
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]

[params.posts]
    foldername = "post"
    pagesize = "6"
    featuredpost= "true"

[params.settings]
    googleanalytics = "UA-118141496-1"
    disqus = "hugo-massively"
    
[blackfriday]
  hrefTargetBlank = true
    
[menu]
    [[menu.main]]
  	name="Home"
  	identifier="home"
  	url="/"
	weight=1

   [[menu.main]]
  	name="Photographie"
  	identifier="about"
  	url="/about/"
	weight=2
	
	[[menu.main]]
  	name="Video"
  	identifier="news"
  	url="/post/"
	weight=3
	
	[[menu.main]]
  	name="Illustration"
  	identifier="ideas"
  	url="/ideas/"
	weight=4
	
	[[menu.main]]
  	name="News"
  	identifier="sst2018"
  	url="/sst2018/"
	weight=5
	


	
      